# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: Sync labels

on:
  push:
    branches:
    - main
    paths:
    - .github/labels.yml
    - .github/workflows/label-sync.yml

permissions:
  issues: write

jobs:
  build:
    name: Sync labels
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: srealmoreno/label-sync-action@v1
      with:
        clean-labels: true
