# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Docker Hub Description
on:
  push:
    branches:
    - main
jobs:
  sync-readme:
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'WeblateOrg/wlc' }}
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: weblate/wlc
