# This file is maintained in https://github.com/WeblateOrg/meta/

name: "Close stale"
on:
  schedule:
    - cron: "30 1 * * *"
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/stale.yml

jobs:
  stale-issues:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v3
        with:
          # Ideal setup would be 10/4 for issues and 30/14 for PRs, but not supported, see
          # https://github.com/actions/stale/issues/214
          days-before-stale: 20
          days-before-close: 8
          exempt-issue-labels: bug,enhancement,documentation,security
          stale-issue-label: wontfix
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had any recent activity.

            It will be closed soon if no further action occurs.

            Thank you for your contributions!
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had any recent activity.

            It will be closed soon if no further action occurs.

            Thank you for your contributions!
